variables:
  MUMBLE_ENVIRONMENT_STORE: '$(Agent.ToolsDirectory)/MumbleBuild'
  MUMBLE_ENVIRONMENT_SOURCE: 'https://dl.mumble.info/build/vcpkg'
  MUMBLE_ENVIRONMENT_PATH: '$(MUMBLE_ENVIRONMENT_STORE)/$(MUMBLE_ENVIRONMENT_VERSION)'
  MUMBLE_ENVIRONMENT_TOOLCHAIN: '$(MUMBLE_ENVIRONMENT_PATH)/scripts/buildsystems/vcpkg.cmake'

jobs:
  - job: Windows_x86_64
    displayName: Windows (x86_64)
    pool:
      vmImage: 'windows-latest'
    variables:
      MUMBLE_ENVIRONMENT_VERSION: 'win64-static-1.4.x-2020-07-22-dbd6271-1162'
      MUMBLE_ENVIRONMENT_TRIPLET: 'x64-windows-static-md'
      VCVARS_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
    steps:
    - template: steps_windows.yml
      parameters:
        arch: 'x64'
  - job: Windows_x86
    displayName: Windows (x86)
    pool:
      vmImage: 'windows-latest'
    variables:
      MUMBLE_ENVIRONMENT_VERSION: 'win32-static-1.4.x-2020-07-22-dbd6271-1162'
      MUMBLE_ENVIRONMENT_TRIPLET: 'x86-windows-static-md'
      VCVARS_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsamd64_x86.bat'
    steps:
    - template: steps_windows.yml
      parameters:
        arch: 'x86'
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: steps_linux.yml
  - job: macOS
    pool:
      vmImage: 'macOS-latest'
    variables:
      MUMBLE_ENVIRONMENT_VERSION: 'macos-static-1.4.x-2020-07-22-dbd6271-1162'
    steps:
    - template: steps_macos.yml
      parameters:
        installEnvironment: true
  - job: Translations
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: .ci/azure-pipelines/install-environment_linux_translations.bash
      displayName: 'Install Qt tools'
    - script: .ci/azure-pipelines/assertNoTranslationChanges.sh
      displayName: 'Checking for translation changes'
  - job: Docs
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      submodules: false
      fetchDepth: 1
    - script: .ci/azure-pipelines/checkDocs.bash
      displayName: 'Check documentation'
