steps:
  - script: git submodule --quiet update --init --recursive
    displayName: 'Fetch submodules'
  - powershell: .ci/azure-pipelines/install-environment_windows.ps1
    displayName: 'Install build environment'
  - script: .ci/azure-pipelines/build_windows.bat
    env:
      MUMBLE_BUILD_NUMBER_TOKEN: $(BUILD_NUMBER_TOKEN)
    displayName: 'Build'
  - template: task-publish-artifacts.yml
    parameters:
      name: 'Windows (${{parameters.arch}}) installer'
