steps:
  - script: git submodule --quiet update --init --recursive
    displayName: 'Fetch submodules'
  - script: .ci/azure-pipelines/install-environment_linux.bash
    displayName: 'Install build environment'
  - script: .ci/azure-pipelines/build_linux.bash
    displayName: 'Build'
  - script: .ci/azure-pipelines/package_AppImage.bash
    displayName: 'Package AppImage'
  - template: task-publish-artifacts.yml
    parameters:
      name: "AppImage" 
