name: Backport PRs

on:
  pull_request_target:
    types: ["labeled", "closed"]

jobs:
  backport:
  - name: Check labels
    id: label_check
    uses: docker://agilepathway/pull-request-label-checker:latest
    with:
      prefix_mode: true
      all_of: auto-backport-to-
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      allow_failure: true

  - name: Backport PR
    if: github.event.pull_request.merged == true && steps.label_check.outputs.label_check == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Backport Action
        uses: sorenlouv/backport-github-action@v9.5.1
        with:
          github_token: ${{ secrets.BACKPORT_TOKEN }}
          auto_backport_label_prefix: auto-backport-to-

      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log
        
      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log        
